stages:
  - build-resources
  - build-tex
  - convert-pptx

build-tex:
  image:
    name: texlive/texlive
  stage: build-tex
  script:
    - cd praktikum/
    - make pdf
  artifacts:
    untracked: true
    expire_in: 1 week
    paths:
      - "tex/*.pdf"
  when: on_success

convert-pptx:
  image:
    name: ghcr.io/snicki13/libreoffice-docker:main
  stage: convert-pptx
  script:
    - cd vorlesung
    - make pptx
    - make staple
  artifacts:
    untracked: true
    expire_in: 1 week
    paths:
      - "pptx/*.pdf"
  when: on_success
